server:
  port: 8083

spring.application.name: users

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      #defaultZone: ${EUREKA_URI:http://172.18.0.22:8761/eureka}