version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    container_name: eureka-server
    hostname: eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
  zuul-server:
    image: zuul-server
    build:
      context: ./zuul-server
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - 8762:8762
    container_name: zuul-server
    hostname: zuul-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - ZUUL_ROUTES_OAUTH_URL=http://oauth:8889/oauth
      - ZUUL_ROUTES_USERS_URL=http://users:0/todolist/users
  users:
    image: users
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    container_name: users
    hostname: users
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=todolist
      - JWT_BASEURL=http://oauth:8889
  oauth:
    image: oauth
    build:
      context: ../spring-oauth2
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - 8889:8889
    container_name: oauth
    hostname: oauth
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=oauthserver



# variables from environment correspond to links(variables from yaml) used by apps but written with uppercase
# and : replaced by _
#localhost correspond to name of the service that is called