server:
  port: 8762
spring:
  application:
    name: zuul-server

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.18.0.22:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    users:
      url: http://172.18.0.25:8083/todolist/users
    oauth:
      url: http://172.18.0.26:8889/oauth

ribbon.eureka.enabled: false
