spring:
  application:
    name: todo
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
      token: eyJhbGciOiJSUzUxMiJ9.eyJhdXRoIjpbeyJhdXRob3JpdHkiOiJST0xFX0FETUlOIn1dLCJzdWIiOiJhZG1pbiIsImlhdCI6MTU4MTQxNDQ3NywiZXhwIjoxMzYwMDk5NDQwMH0.Be22RfnaRQBwaxf3lixWbMSQTrCdyWflreQ0-T_foP5Cpp-0VzKez3qa67s866vDUq8pwYteSastaqTarYhEz1jHCxfn0PPG-PgqstraSJgrVs8y0IBQydY7fizXRCYJzMzg0ULzyVMJ2mG_0u16Mr_Lmva2YgZ2h5UdaJJsZYw
      username: root
      password: s3cr3t

#server:
#  port: ${PORT:0}
#
#eureka:
#  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  jpa:
    properties:
      hibernate:
        show-sql: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        jdbc:
          batch_size: 2
        order_inserts: true
        order_updates: true
        generate_statistics: true

server:
  port: 8085

