spring:
  profiles:
    active: @spring.profiles.active@
    include: todo, user

certificate:
  alias: jwtcert
  nameAndPath: keystore.jks
  url: /oauth/auth_asym_key/certificate
  bits: 1024

#server.servlet.context-path: /todolist


