spring:
  profiles:
    active: @spring.profiles.active@
    include: todo-dev

certificate:
    alias: jwtcert
    name: data/keystore.jks
    nameAndPath: commons/src/main/resources/data/keystore.jks
    url: /auth_asym_key/certificate
    bits: 1024


