server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: file:///classpath:./config
          timeout: 10
          clone-on-start: true

  security:
    user:
      name: root
      password: s3cr3t